# `dist/index.js` is a special file in Actions.
# When you reference an action with `uses:` in a workflow,
# `index.js` is the code that will run.
# For our project, we generate this file through a build process from other source files.
# We need to make sure the checked-in `index.js` actually matches what we expect it to be.
name: main pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build_and_stuff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: MM12300/portfolio-CICD/checkout-main@main
        with:
          repository: MM12300/angular-tour-of-heroes
          ref: 'master'
          token: ${{ secrets.TOKEN_GITHUB }}


      - name: Setup Node 14.x
        uses: MM12300/portfolio-CICD/setup-node-main@main
        with:
          action: action.yml
          node-version: 14.x

      - name: Install dependencies
        run: npm ci

      - name: Rebuild the dist/ directory
        run: npm run build
#
      - name: Compare the expected and actual dist/ directories
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            exit 1
          fi
        id: diff

#      # If index.js was different than expected, upload the expected version as an artifact
#      - uses: MM12300/portfolio-CICD@main
#        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
#        with:
#          action : upload-artifact.yml
#          name: dist
#          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_stuff
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: MM12300/portfolio-CICD/upload-artifact-main@main
        with:
          name: angular-app
          path: dist/

#      - name: 'Deploy to Azure Web App'
#        id: deploy-to-webapp
#        uses: Maxime-DO/actions_azure_webapps-deploy@v2
#        with:
#          app-name: 'MMportfolio'
#          slot-name: 'Production'
#          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B4A298A01C22454BBD7FE39FE0608DC5 }}
#          package: .
