# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - MMportfolio

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: MM12300/portfolio-CICD/checkout-main@main
        with:
          repository: MM12300/angular-tour-of-heroes
          ref: 'master'
          token: ${{ secrets.TOKEN_GITHUB }}

      - name: Set up Node.js version
        uses: MM12300/portfolio-CICD/setup-node-main@main
        with:
          node-version: '14.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present

      - name: Upload artifact for deployment job
        uses: MM12300/portfolio-CICD/upload-artifact-main@main
        with:
          name: angular-tour-of-heroes-1
          path: ./dist/angular-tour-of-heroes


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: MM12300/portfolio-CICD/download-artifact-main@main
        with:
          name: angular-tour-of-heroes-1

      - name : pwd
        run : pwd

      - name : ls
        run : ls -alh

      - name: Azure Login
        uses: MM12300/portfolio-CICD/login-master@main
        with :
          creds: ${{ secrets.AZURE_CREDENTIALS}}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: MM12300/portfolio-CICD/webapps-deploy-master@main
        with:
          app-name: angular-tour-of-heroes-1
          publish-profile:  ${{ secrets.AzureAppService_PublishProfile_541fff7d309c4827b939c14e443b387e }}
          package: dist/angular-tour-of-heroes-1
