# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - MMportfolio

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: MM12300/portfolio-CICD/checkout-main@main

      - name: Set up Node.js version
        uses: MM12300/portfolio-CICD/setup-node-main@main
        with:
          node-version: '14.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present

      - name : test ls
        run : ls -lha

      - name: test ls
        run: ls -alh dist

      - name: Upload artifact for deployment job
        uses: MM12300/portfolio-CICD/upload-artifact-main@main
        with:
          name: angular-tour-of-heroes
          path: ./dist/angular-tour-of-heroes



  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: MM12300/portfolio-CICD/download-artifact-main@main
        with:
          name: angular-tour-of-heroes

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: MM12300/portfolio-CICD/webapps-deploy-master@main
        with:
          app-name: 'MMportfolio'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_37DAF39DCDAD4CA299224012C463714D }}
          package: .
